export const navigationConfig = {
  transformations: [
    { href: '/transformations/lab-1', label: 'Lab 01' },
    { href: '/transformations/lab-2', label: 'Lab 02' },
    { href: '/transformations/lab-3', label: 'Lab 03' },
    { href: '/transformations/lab-4', label: 'Lab 04' },
    { href: '/transformations/lab-5', label: 'Lab 05' },
    { href: '/transformations/lab-6', label: 'Lab 06' },
  ],
  transitions: [
    { href: '/transitions/lab-1', label: 'Lab 01' },
    { href: '/transitions/lab-2', label: 'Lab 02' },
    { href: '/transitions/lab-3', label: 'Lab 03' },
    { href: '/transitions/lab-4', label: 'Lab 04' },
    { href: '/transitions/lab-5', label: 'Lab 05' },
    { href: '/transitions/lab-6', label: 'Lab 06' },
  ],
  keyframes: [
    { href: '/keyframes/lab-1', label: 'Lab 01' },
    { href: '/keyframes/lab-2', label: 'Lab 02' },
    { href: '/keyframes/lab-3', label: 'Lab 03' },
    { href: '/keyframes/lab-4', label: 'Lab 04' },
    { href: '/keyframes/lab-5', label: 'Lab 05' },
    { href: '/keyframes/lab-6', label: 'Lab 06' },
    { href: '/keyframes/lab-7', label: 'Lab 07' },
  ],
  variants: [
    { href: '/variants/lab-1', label: 'Lab 01' },
    { href: '/variants/lab-2', label: 'Lab 02' },
    { href: '/variants/lab-3', label: 'Lab 03' },
    { href: '/variants/lab-4', label: 'Lab 04' },
    { href: '/variants/lab-5', label: 'Lab 05' },
  ],
  gestures: [
    { href: '/gestures/lab-1', label: 'Lab 01' },
    { href: '/gestures/lab-2', label: 'Lab 02' },
    { href: '/gestures/lab-3', label: 'Lab 03' },
    { href: '/gestures/lab-4', label: 'Lab 04' },
    { href: '/gestures/lab-5', label: 'Lab 05' },
    { href: '/gestures/lab-6', label: 'Lab 06' },
  ],
  staggers: [
    { href: '/staggers/lab-1', label: 'Lab 01' },
    { href: '/staggers/lab-2', label: 'Lab 02' },
    { href: '/staggers/lab-3', label: 'Lab 03' },
    { href: '/staggers/lab-4', label: 'Lab 04' },
    { href: '/staggers/lab-5', label: 'Lab 05' },
  ],
  motionValue: [
    { href: '/motion-value/lab-1', label: 'Lab 01' },
    { href: '/motion-value/lab-2', label: 'Lab 02' },
    { href: '/motion-value/lab-3', label: 'Lab 03' },
    { href: '/motion-value/lab-4', label: 'Lab 04' },
  ],
  whileInView: [
    { href: '/while-in-view/lab-1', label: 'Lab 01' },
    { href: '/while-in-view/lab-2', label: 'Lab 02' },
    { href: '/while-in-view/lab-3', label: 'Lab 03' },
  ],
};
